baseURL = "https://kubevisor.io/"
languageCode = "en-us"
title = "Kubevisor"
theme = "kube"

[params]
author = "Link Society"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pre = "<i class='fas fa-rss-square'></i>"
    url = "/blog/"
    weight = -110

  [[menu.main]]
    name = "Documentation"
    pre = "<i class='fa fa-info-circle'></i>"
    url = "/docs/"
    weight = -100
